"""contraints changed

Revision ID: 3320c36bc366
Revises: d0e40321655d
Create Date: 2025-01-03 15:21:03.574969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3320c36bc366'
down_revision = 'd0e40321655d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
